services:
  - type: web
    name: propview
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install --include=dev && NODE_OPTIONS="--dns-result-order=ipv4first" npm run build && cp -r public .next/standalone/public && cp -r .next/static .next/standalone/.next/static
    startCommand: node .next/standalone/server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: NODE_OPTIONS
        value: "--dns-result-order=ipv4first"
